services:
  ntp:
    image: chronyd-s811:latest
    container_name: ntp
    environment:
      LOG_LEVEL: 0
#      ENABLE_SYSCLK: "true"
    ports:
      - 123:123/udp
    restart: unless-stopped
    volumes:
      - ./config:/etc/chrony
