services:
  ntp:
    image: chronyd-s811:latest
    container_name: ntp-server
    cap_add:
    - SYS_TIME
    environment:
      LOG_LEVEL: 0
      ENABLE_SYSCLK: "true"
    ports:
      - 123:123/udp
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/chrony:ro
